# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-kishu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd kishu
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py install
        python -c "import kishu, kishu.cli, kishu.backend, kishu.commands"
    - name: Install development dependencies
      run: |
        cd kishu
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd kishu
        flake8 kishu/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 kishu/ tests/ --count --max-complexity=100 --max-line-length=127 --statistics
    - name: Check Python files with Mypy
      run: |
        cd kishu
        mypy **/*.py
    - name: Test Kishu with pytest
      run: |
        cd kishu
        if [ "${{ matrix.python-version }}" == "3.8" ]; then
          pytest -s --cov=kishu/ --cov-report=xml;
        else
          pytest -s
        fi
    - name: Upload coverage reports to Codecov
      if:  matrix.python-version == '3.8'
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
